import { building } from '$app/environment';
import { type Handle, type HandleServerError, redirect } from '@sveltejs/kit';
import { sequence } from '@sveltejs/kit/hooks';
import { ensureAdminUser } from '$lib/server/auth/seed';
import { SESSION_COOKIE, validateSession } from '$lib/server/auth/session';
import { getDb } from '$lib/server/db';

// The Content-Security-Policy header is generated by SvelteKit (see `csp` in
// vite.config.ts) so that its inline hydration scripts get nonces instead of
// requiring 'unsafe-inline'.
const securityHeaders: Handle = async ({ event, resolve }) => {
	const response = await resolve(event);
	response.headers.set('X-Frame-Options', 'DENY');
	response.headers.set('X-Content-Type-Options', 'nosniff');
	response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
	response.headers.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
	return response;
};

const database: Handle = async ({ event, resolve }) => {
	event.locals.db = getDb(event.platform);
	return resolve(event);
};

const auth: Handle = async ({ event, resolve }) => {
	const token = event.cookies.get(SESSION_COOKIE);
	event.locals.user = token ? await validateSession(event.locals.db, token) : null;
	return resolve(event);
};

const adminGuard: Handle = async ({ event, resolve }) => {
	if (event.route.id?.startsWith('/admin') && !event.locals.user) {
		throw redirect(303, '/login');
	}

	return resolve(event);
};

// Seed the admin account once per process instead of querying on every request.
let adminSeeded = false;

const bootstrap: Handle = async ({ event, resolve }) => {
	if (!building && !adminSeeded) {
		await ensureAdminUser(event.locals.db, event.platform);
		adminSeeded = true;
	}
	return resolve(event);
};

export const handle = sequence(securityHeaders, database, bootstrap, auth, adminGuard);

export const handleError: HandleServerError = ({ error }) => {
	if (!building) {
		console.error(error);
	}

	return {
		message: 'Something went wrong. Please try again.'
	};
};
